{{- if .Values.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "cloudflare-tunnel-remote.fullname" . }}
  {{- with .Values.metrics.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "cloudflare-tunnel-remote.labels" . | nindent 4 }}
  {{- with .Values.metrics.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ default "app.kubernetes.io/name" .Values.metrics.podMonitor.jobLabel }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "cloudflare-tunnel-remote.selectorLabels" . | nindent 6 }}
  {{- with .Values.metrics.podMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
    {{- with .Values.metrics.podMonitor.endpointConfig }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}