# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
{{- if and (.Values.cloudflare.tunnel_token) (not .Values.cloudflare.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel-remote.fullname" . }}
  labels:
    {{- include "cloudflare-tunnel-remote.labels" . | nindent 4 }}
stringData:
  tunnelToken: {{ .Values.cloudflare.tunnel_token }}
{{- end }}
