{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "argo-tunnel.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "argo-tunnel.roleName" . }}
rules:
- apiGroups:
  - ""
  - "extensions"
  resources:
  - endpoints
  - ingresses
  - services
  - secrets
  verbs:
  - list
  - get
  - watch
{{- end }}
