apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "argo-tunnel.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "argo-tunnel.fullname" . }}
spec:
  {{- if .Values.loadBalancing.enabled }}
  replicas: {{ .Values.controller.replicaCount }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "argo-tunnel.name" . }}
      component: {{ .Values.controller.name }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "argo-tunnel.name" . }}
        component: {{ .Values.controller.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "argo-tunnel.name" . }}-{{ .Values.controller.name }}
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
        command: ["argot", "couple"]
        args:
        - --incluster
        - --ingress-class={{ .Values.controller.ingressClass }}
        {{- if .Values.controller.defaultOriginSecret }}
        - --default-origin-secret={{ .Values.controller.defaultOriginSecret }}
        {{- end }}
        {{- if .Values.secretMapping.create }}
        - --origin-secret-config=/etc/argo/secret-mapping.yaml
        {{- end }}
        {{- if .Values.controller.repairDelay }}
        - --repair-delay={{ .Values.controller.repairDelay }}
        {{- end }}
        {{- if .Values.controller.repairJitter }}
        - --repair-jitter={{ .Values.controller.repairJitter }}
        {{- end }}
        {{- if .Values.controller.resyncPeriod }}
        - --resync-period={{ .Values.controller.resyncPeriod }}
        {{- end }}
        {{- if .Values.controller.tagLimit }}
        - --tag-limit={{ .Values.controller.tagLimit }}
        {{- end }}
        {{- if .Values.controller.transportLogEnable }}
        - --transport-log-enable
        {{- end }}
        {{- if .Values.controller.watchNamespace }}
        - --watch-namespace={{ .Values.controller.watchNamespace }}
        {{- end }}
        {{- if .Values.controller.workers }}
        - --workers={{ .Values.controller.workers }}
        {{- end }}
        - --v={{ .Values.controller.logLevel }}
        {{- if .Values.controller.resources }}
        resources:
{{ toYaml .Values.controller.resources | trim | indent 10 }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        {{- if .Values.secretMapping.create }}
        volumeMounts:
        - mountPath: /etc/argo
          name: {{ template "argo-tunnel.fullname" . }}
          readOnly: true
        {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      {{- if or .Values.serviceAccount.create .Values.rbac.create }}
      serviceAccount: {{ template "argo-tunnel.serviceAccountName" . }}
      serviceAccountName: {{ template "argo-tunnel.serviceAccountName" . }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      {{- if .Values.secretMapping.create }}
      volumes:
      - name: {{ template "argo-tunnel.fullname" . }}
        configMap:
          name: {{ template "argo-tunnel.fullname" . }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{ template "argo-tunnel.name" . }}
                  component: {{ .Values.controller.name }}
                  release: {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
