{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.metrics.port }}
    name: http-metrics
    targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "cloudflare-tunnel.selectorLabels" . | nindent 4 }}
{{- end }}