{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "argo-tunnel.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "argo-tunnel.roleName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "argo-tunnel.roleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "argo-tunnel.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
