{{- if or .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "argo-tunnel.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "argo-tunnel.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
