name: Release Charts to OCI

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: read
      packages: write # Crucial: Allows the action to push OCI packages to GHCR

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and Push Helm Charts
        run: |
          # GHCR requires the namespace (repository owner) to be entirely lowercase
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          # Iterate over each directory in the charts folder
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              echo "Packaging $chart..."
              
              # Package the chart and extract the generated file path
              PKG_PATH=$(helm package "$chart" | awk '{print $NF}')
              
              echo "Pushing $PKG_PATH to GHCR..."
              
              # Push the packaged chart to the OCI registry
              helm push "$PKG_PATH" oci://ghcr.io/$REPO_OWNER
            fi
          done